pipeline {
    agent any // Use any available agent
    parameters {
        string(name: 'DataBaseName', defaultValue: 'my-new-postgresql-16-database', description: 'Enter you database Name Here:')
        password(name: 'ROOT_PASSWORD', defaultValue: 'rootpassword', description: 'Enter your Password for Postgresql:')
        string(name: 'request', defaultValue: 'None', description: 'Executor Name')
        string(name: 'requestorType', defaultValue: 'None', description: 'Execution project Name')
    }

    environment {
        CHART_REL_LINK1 = 'helm-charts/postgresql-16'
        //CHART_REL_LINK2 = 'helm-charts/percona-mysql/ps-db'
        VALUES_FILE = 'values.yaml'
        KUB_NAMESPACE = 'databases'
        GIT_BRANCH = 'databases'
        CHART_NAME1 = 'postgresql-16'
        //CHART_NAME2 = 'mysql-percona-db-jen-test'password
        BIT_SECRET = credentials('BITBUCKET_INNOCLOUD_READ')
        GIT_SSH_COMMAND = 'ssh -o StrictHostKeyChecking=no'
    }

    stages {
        stage('Check Kube') {
            steps {
                echo "Running kubectl test"
                script {
                    // Ensure KUBECONFIG is set properly
                    withCredentials([file(credentialsId: 'k8s', variable: 'KUBECONFIG')]) {
                        sh "kubectl describe service --all-namespaces | grep -i nodeport"

                    }
                }
            }
        }

        stage('Install/Update Helm chart') {
            steps {
                // Assuming you're using credentials plugin to store your harbor credentials
                withCredentials([
                                 file(credentialsId: 'k8s' , variable: 'KUBECONFIG'),
                                 usernamePassword(credentialsId: 'HarborCredentials', passwordVariable: 'PASSWORD_VAR', usernameVariable: 'USERNAME')]) {
                  sh   '''
                       #!/bin/bash
                       set -e  
                         
                
                       git clone --filter=blob:none --no-checkout https://$BIT_SECRET@bitbucket.org/innowise-group/devops.git
                       cd devops/
                       git sparse-checkout set --cone
                       git checkout $GIT_BRANCH
                       git sparse-checkout set $CHART_REL_LINK1
                       helm dependency build $CHART_REL_LINK1
                       helm list -a -n $KUB_NAMESPACE | grep "postgresql-16" | awk "{print $1}" | xargs -r -I % helm uninstall % -n $KUB_NAMESPACE
                       helm install $CHART_NAME1  -f $CHART_REL_LINK1/$VALUES_FILE $CHART_REL_LINK1 --namespace $KUB_NAMESPACE --set auth.postgresPassword="${params.ROOT_PASSWORD}"
                       
                       
                       '''
                       // --set auth.postgresPassword="${params.ROOT_PASSWORD}"
                       // helm install $CHART_NAME1-${params.DataBaseName} $CHART_REL_LINK1 -f $CHART_REL_LINK1/$VALUES_FILE --namespace $KUB_NAMESPACE --set auth.postgresPassword="${params.ROOT_PASSWORD}"
                      
                }
            }
        }
    }
    post {
        always {
            script {
                try {
                
                 def file = notificator(params.request, params.requestorType)
                 
                }
                catch (java.io.NotSerializableException e)
                {}
                 }
        }
    }
}